### ISSUE TITLE
cannot install postgres-metric dependency `pg` using embedded `gem`

### ISSUE THREAD

**Issue by mateodelnorte** [sensu/sensu-community-plugins#1037]
Hi all,

I'm doing a `/opt/sensu/embedded/bin/gem install pg` on CentOS 7 using ansible for deployment, and seeing a failed install. Ruby version `ruby 2.0.0p353 (2013-11-22 revision 43784) [x86_64-linux]`

```
[root@nj1sredis01 ~]# /opt/sensu/embedded/bin/gem install pg
Building native extensions.  This could take a while...
ERROR:  Error installing pg:
	ERROR: Failed to build gem native extension.

    /opt/sensu/embedded/bin/ruby extconf.rb
checking for pg_config... yes
Using config values from /usr/bin/pg_config
checking for libpq-fe.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/sensu/embedded/bin/ruby
	--with-pg
	--without-pg
	--enable-windows-cross
	--disable-windows-cross
	--with-pg-config
	--without-pg-config
	--with-pg_config
	--without-pg_config
	--with-pg-dir
	--without-pg-dir
	--with-pg-include
	--without-pg-include=${pg-dir}/include
	--with-pg-lib
	--without-pg-lib=${pg-dir}/
/opt/sensu/embedded/lib/ruby/2.0.0/mkmf.rb:434:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /opt/sensu/embedded/lib/ruby/2.0.0/mkmf.rb:565:in `try_cpp'
	from /opt/sensu/embedded/lib/ruby/2.0.0/mkmf.rb:1097:in `block in find_header'
	from /opt/sensu/embedded/lib/ruby/2.0.0/mkmf.rb:895:in `block in checking_for'
	from /opt/sensu/embedded/lib/ruby/2.0.0/mkmf.rb:340:in `block (2 levels) in postpone'
	from /opt/sensu/embedded/lib/ruby/2.0.0/mkmf.rb:310:in `open'
	from /opt/sensu/embedded/lib/ruby/2.0.0/mkmf.rb:340:in `block in postpone'
	from /opt/sensu/embedded/lib/ruby/2.0.0/mkmf.rb:310:in `open'
	from /opt/sensu/embedded/lib/ruby/2.0.0/mkmf.rb:336:in `postpone'
	from /opt/sensu/embedded/lib/ruby/2.0.0/mkmf.rb:894:in `checking_for'
	from /opt/sensu/embedded/lib/ruby/2.0.0/mkmf.rb:1096:in `find_header'
	from extconf.rb:47:in `<main>'


Gem files will remain installed in /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/pg-0.18.1 for inspection.
Results logged to /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/pg-0.18.1/ext/gem_make.out
```
Should have all the necessary libs `yum`-installed:
```
postgresql.x86_64                       9.2.7-1.el7                    @base
postgresql-devel.x86_64                 9.2.7-1.el7                    @base
postgresql-libs.x86_64                  9.2.7-1.el7                    @base
postgresql-server.x86_64                9.2.7-1.el7                    @base
libpqxx.x86_64                          1:4.0.1-1.el7                  @epel
libpqxx-devel.x86_64                    1:4.0.1-1.el7                  @epel
```

Anyone have ideas for a fix on CentOS 7?

**Comment by mattyjones** [comment]
http://stackoverflow.com/questions/6040583/cant-find-the-libpq-fe-h-header-when-trying-to-install-pg-gem

I don't have a cent7 vagrantbox handy atm using the embedded ruby but the above link may be helpful.  The new gems will be tested against this so fear not(in the future) ;)

**Comment by mateodelnorte** [comment]
This didn't work, post install. But it may be that I need to uninstall and
reinstall sensu after having added this package...

**Comment by bkett** [comment]
@mateodelnorte It could be something in CentOS7 is fundamentally different than 6 with regards to the development tools. It's not something I'm overly familiar with.

**Comment by mikeroth** [comment]
yum install gcc

**Comment by mattyjones** [comment]
@mateodelnorte  Are you all set, did the above suggestions work you.
