### ISSUE TITLE
If sensu-api process is down, TTL extension causes sensu-server process to crash

### ISSUE THREAD

**Issue by exsortis** [sensu/sensu-community-plugins#1084]
I noticed that when the Sensu API process is unavailable for any reason, and the TTL extension attempts to establish a connection (and obviously fails), it brings down the entire sensu-server process. This is a Bad Thing(tm).

```
/opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:878:in `initialize': Connection refused - connect(2) (Errno::ECONNREFUSED)
	from /opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:878:in `open'
	from /opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
	from /opt/sensu/embedded/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
	from /opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:877:in `connect'
	from /opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from /opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:1367:in `request'
	from /etc/sensu/extensions/handlers/ttl.rb:122:in `api_request'
	from /etc/sensu/extensions/handlers/ttl.rb:109:in `api_get'
	from /etc/sensu/extensions/handlers/ttl.rb:77:in `periodic_ttl_expiration'
	from /etc/sensu/extensions/handlers/ttl.rb:50:in `block in post_init'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/em/timers.rb:56:in `call'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/em/timers.rb:56:in `fire'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/eventmachine.rb:187:in `call'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/eventmachine.rb:187:in `run_machine'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/eventmachine.rb:187:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.16.0/lib/sensu/server.rb:13:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.16.0/bin/sensu-server:10:in `<top (required)>'
	from /opt/sensu/bin/sensu-server:23:in `load'
	from /opt/sensu/bin/sensu-server:23:in `<main>'
```

**Comment by mattyjones** [comment]
@portertech
