### ISSUE TITLE
mongodb-metrics.rb - Check failed to run: uninitialized constant MongoDB::True

### ISSUE THREAD

**Issue by FlorinAndrei** [sensu/sensu-community-plugins#1093]
I keep getting this error:

```
Check failed to run: uninitialized constant MongoDB::True, ["./mongodb-metrics.rb:68:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.1.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'"]
```

Not sure what's wrong. Other plugins such as check-disk.rb work just fine. What's the first thing I should investigate?

BTW, for mongodb-metrics.rb and a mongod that only accepts SSL connections, I had to change line 68 to:

```
    mongo_client = MongoClient.new(host, port, ssl=True)
```

Without ssl=True it fails with:

```
Check failed to run: Operation failed with the following exception: end of file reached, ["/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/mongo-1.12.0/lib/mongo/networking.rb:338:in `rescue in receive_message_on_socket'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/mongo-1.12.0/lib/mongo/networking.rb:330:in `receive_message_on_socket'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/mongo-1.12.0/lib/mongo/networking.rb:191:in `receive_header'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/mongo-1.12.0/lib/mongo/networking.rb:182:in `receive'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/mongo-1.12.0/lib/mongo/networking.rb:146:in `receive_message'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/mongo-1.12.0/lib/mongo/cursor.rb:551:in `block in send_initial_query'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/mongo-1.12.0/lib/mongo/functional/logging.rb:55:in `block in instrument'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/mongo-1.12.0/lib/mongo/functional/logging.rb:20:in `instrument'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/mongo-1.12.0/lib/mongo/functional/logging.rb:54:in `instrument'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/mongo-1.12.0/lib/mongo/cursor.rb:547:in `send_initial_query'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/mongo-1.12.0/lib/mongo/cursor.rb:532:in `refresh'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/mongo-1.12.0/lib/mongo/cursor.rb:139:in `next'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/mongo-1.12.0/lib/mongo/db.rb:605:in `command'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/mongo-1.12.0/lib/mongo/mongo_client.rb:542:in `block in check_is_master'", "/opt/sensu/embedded/lib/ruby/2.0.0/timeout.rb:66:in `timeout'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/mongo-1.12.0/lib/mongo/mongo_client.rb:541:in `check_is_master'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/mongo-1.12.0/lib/mongo/mongo_client.rb:395:in `connect'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/mongo-1.12.0/lib/mongo/mongo_client.rb:656:in `setup'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/mongo-1.12.0/lib/mongo/mongo_client.rb:179:in `initialize'", "./mongodb-metrics.rb:68:in `new'", "./mongodb-metrics.rb:68:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.1.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'"]
```

**Comment by FlorinAndrei** [comment]
Okay, no, this is not a bug - at least not in the sense I thought initially. This is actually due to the plugin not having any form of SSL mode in it. If your MongoDB only accepts SSL connections, this plugin will fail.

Let me conjure up an SSL patch for this plugin, then I'll do a pull request.

Please leave this issue open until I have the PR going, then I'll link he PR here and I'll close the issue. Thanks!

**Comment by FlorinAndrei** [comment]
Here's the PR:

https://github.com/sensu/sensu-community-plugins/pull/1094

I'm waiting for Travis to give it the green light.

**Comment by FlorinAndrei** [comment]
Okay, it passed, closing this issue.
