### ISSUE TITLE
elasticsearch plugins not working

### ISSUE THREAD

**Issue by codesplicer** [sensu/sensu-community-plugins#1166]
It appears that the elasticsearch plugins es-node-graphite.rb and es-node-metrics.rb are not compatible with v1.x of the sensu-plugin gem. I get the following error when running manually from the embedded ruby:

```shell
Sensu::Plugin::CLI: ["Not implemented! You should override Sensu::Plugin::CLI#run."]
/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require': cannot load such file -- rest-client (LoadError)
	from /opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
	from es-node-graphite.rb:41:in `<main>'
```

Tested on v1.0.0 and v1.1.0 of sensu-plugin gem.

**Comment by codesplicer** [comment]
Turns out it was a missing gem, rest-client that was the root cause. Closing as its a non-issue
