### ISSUE TITLE
docker-container-metrics doesn't seem to work

### ISSUE THREAD

**Issue by soichih** [sensu/sensu-community-plugins#1231]
When I try to execute docker-container-metrics plugin I get following error message

```
2015-08-25 02:48:45 UTC [root@core1:~/docker/monitor/sensu/conf/conf.d]# ruby /usr/local/sensu-community-plugins/plugins/docker/docker-container-metrics.rb
Sensu::Plugin::CLI: ["Not implemented! You should override Sensu::Plugin::CLI#run."]
/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- sys/proctable (LoadError)
        from /opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/sensu-community-plugins/plugins/docker/docker-container-metrics.rb:31:in `<main>'

```

Am I missing something?

I am using sensu's embedded ruby (version 2.0.0.p645)

```
2015-08-25 02:52:18 UTC [root@core1:~/docker/monitor/sensu/conf/conf.d]# which ruby
/opt/sensu/embedded/bin/ruby
```

**Comment by soichih** [comment]
Actually, I am seeing this error message on a whole bunch of other plugins.

```
ruby docker-container-metrics.rb
Sensu::Plugin::CLI: ["Not implemented! You should override Sensu::Plugin::CLI#run."]
/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- sys/proctable (LoadError)
        from /opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from docker-container-metrics.rb:31:in `<main>'
```

```
ruby check-container.rb
Sensu::Plugin::CLI: ["Not implemented! You should override Sensu::Plugin::CLI#run."]
/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- docker (LoadError)
        from /opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from check-container.rb:41:in `<main>'
```

If anyone could help me with this, I'd greatly appreciate it!!
