### ISSUE TITLE
Getting a no implicit conversion of Hash into String error

### ISSUE THREAD

**Issue by kaushiksriram100** [sensu/sensu-community-plugins#1248]
Hi, 
I am trying this integration for the first time. 
I am getting this error when the logstash.rb handler is invoked. 

{"timestamp":"2015-12-10T16:27:58.504048-0800","level":"info","message":"handler output","handler":{"type":"pipe","command":"/etc/sensu/handlers/logstash.rb","name":"logstash"},"output":["/opt/sensu/embedded/lib/ruby/2.0.0/json/common.rb:155:in `initialize': no implicit conversion of Hash into String (TypeError)\n\tfrom /opt/sensu/embedded/lib/ruby/2.0.0/json/common.rb:155:in `new'\n\tfrom /opt/sensu/embedded/lib/ruby/2.0.0/json/common.rb:155:in `parse'\n\tfrom /etc/sensu/handlers/logstash.rb:73:in `handle'\n\tfrom /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:55:in `block in <class:Handler>'\n"]}

logstash.json looks like this: 
[root@dal-appblx003-15 conf.d]# cat logstash.json 
{
   "logstash": {
      "output": "udp",
      "server": "Logstashserver",
      "type": "sensu-logstash",
      "port": 5044
    }
}

The logstash input conf file looks like this
[root@logstashserver]# cat /etc/logstash/conf.d/00-log.conf
    input {
        udp {
            port => 5044
            codec => "json"
            type => "sensu-logstash"
        }
    }

**Comment by kaushiksriram100** [comment]
Take this issue back. I used an older plugin. Found a newer one here https://github.com/sensu-plugins/sensu-plugins-logstash/blob/master/bin/handler-logstash.rb
