### ISSUE TITLE
Check failed to run: invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by johntdyer** [sensu/sensu-community-plugins#802]
Occasionally I get the following exception in the check_procs.rb script on CentOS 5.10

```
{
    "timestamp": "2014-10-05T04:22:41.358116+0000",
    "level": "info",
    "message": "publishing check result",
    "payload": {
        "client": "cdr1.prod.us-east-1.aws.xxxxxx.com",
        "check": {
            "name": "tropo-cdr-proc",
            "issued": 1412482960,
            "command": "if [[ ! -f /var/vchef/cache/.dont_not_start_activemq-OPS-2445 ]] ;then check-procs.rb -p \"(java)+.*(tropo-cdr)+\" -C 1 -c 1 -W 1 -w 1; else echo \"Broker is not supposed to be running OPS-2445, ignoring failure\"; exit 0; fi",
            "executed": 1412482960,
            "duration": 0.457,
            "output": "Check failed to run: invalid byte sequence in US-ASCII, [\"/etc/sensu/plugins/check-procs.rb:59:in `split'\", \"/etc/sensu/plugins/check-procs.rb:59:in `block in read_lines'\", \"/etc/sensu/plugins/check-procs.rb:58:in `popen'\", \"/etc/sensu/plugins/check-procs.rb:58:in `read_lines'\", \"/etc/sensu/plugins/check-procs.rb:84:in `get_procs'\", \"/etc/sensu/plugins/check-procs.rb:91:in `run'\", \"/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-0.3.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'\"]\n",
            "status": 2
        }
    }
}
```

**Comment by jhmartin** [comment]
Still seeing this on CentOS 6.5.  Issue occurs for one check result then clears.

**Comment by JonathanHuot** [comment]
To reproduce the issue, you need to run a command with non-ascii characters in command line.
I've used :
```
bash -c "sleep 120 && echo \"$(cat nonascii_characters.txt)\""
```
