### ISSUE TITLE
unable to use mailer.rb -- can't convert nil into

### ISSUE THREAD

**Issue by alex-leonhardt** [sensu/sensu-community-plugins#852]
hi,

i've been trying to make mailer.rb work but no luck - it's a possibly older version than is on github, but for at least a short period of time it used to work ..

here are the details : 

mailer.rb
```ruby
#!/usr/bin/env ruby
#
# Sensu Handler: mailer
#
# This handler formats alerts as mails and sends them off to a pre-defined recipient.
#
# Copyright 2012 Pal-Kristian Hamre (https://github.com/pkhamre | http://twitter.com/pkhamre)
#
# Released under the same terms as Sensu (the MIT license); see LICENSE
# for details.

require 'rubygems' if RUBY_VERSION < '1.9.0'
require 'sensu-handler'
gem 'mail', '~> 2.5.4'
require 'mail'
require 'timeout'

## patch to fix Exim delivery_method: https://github.com/mikel/mail/pull/546
#module ::Mail
#  class Exim < Sendmail
#    def self.call(path, arguments, destinations, encoded_message)
#      popen "#{path} #{arguments}" do |io|
#        io.puts encoded_message.to_lf
#        io.flush
#      end
#    end
#  end
#end

class Mailer < Sensu::Handler
  def short_name
    @event['client']['name'] + '/' + @event['check']['name']
  end

  def action_to_string
   @event['action'].eql?('resolve') ? "RESOLVED" : "ALERT"
  end

  def status_to_string
    case @event['check']['status']
    when 0
      'OK'
    when 1
      'WARNING'
    when 2
      'CRITICAL'
    else
      'UNKNOWN'
    end
  end
  def build_mail_to_list
    mail_to = settings['mailer']['mail_to']
    if settings['mailer'].has_key?('subscriptions')
      @event['check']['subscribers'].each do |sub|
        if settings['mailer']['subscriptions'].has_key?(sub)
          mail_to << ", #{settings['mailer']['subscriptions'][sub]['mail_to']}"
        end
      end
    end
    mail_to
  end

  def handle
    admin_gui = settings['mailer']['admin_gui'] || 'http://localhost:8080/'
    mail_to = build_mail_to_list
    mail_from =  settings['mailer']['mail_from']

    delivery_method = settings['mailer']['delivery_method'] || 'smtp'
    smtp_address = settings['mailer']['smtp_address'] || 'localhost'
    smtp_port = settings['mailer']['smtp_port'] || '25'
    smtp_domain = settings['mailer']['smtp_domain'] || 'localhost.localdomain'

    smtp_username = settings['mailer']['smtp_username'] || nil
    smtp_password = settings['mailer']['smtp_password'] || nil
    smtp_authentication = settings['mailer']['smtp_authentication'] || :plain
    smtp_enable_starttls_auto = settings['mailer']['smtp_enable_starttls_auto'] == "false" ? false : true

    playbook = "Playbook:  #{@event['check']['playbook']}" if @event['check']['playbook']
    body = <<-BODY.gsub(/^\s+/, '')
            #{@event['check']['output']}
            Admin GUI: #{admin_gui}
            Host: #{@event['client']['name']}
            Timestamp: #{Time.at(@event['check']['issued'])}
            Address:  #{@event['client']['address']}
            Check Name:  #{@event['check']['name']}
            Command:  #{@event['check']['command']}
            Status:  #{status_to_string}
            Occurrences:  #{@event['occurrences']}
            #{playbook}
          BODY
    subject = "#{action_to_string} - #{short_name}: #{status_to_string}"
    Mail.defaults do
      delivery_options = {
        :address    => smtp_address,
        :port       => smtp_port,
        :domain     => smtp_domain,
        :openssl_verify_mode => 'none',
        :enable_starttls_auto => smtp_enable_starttls_auto
      }

      unless smtp_username.nil?
        auth_options = {
          :user_name        => smtp_username,
          :password         => smtp_password,
          :authentication   => smtp_authentication
        }
        delivery_options.merge! auth_options
      end

      delivery_method delivery_method.intern, delivery_options
    end

    begin
      timeout 10 do
        Mail.deliver do
          to      mail_to
          from    mail_from
          subject subject
          body    body
        end

        puts 'mail -- sent alert for ' + short_name + ' to ' + mail_to.to_s
      end
    rescue Timeout::Error
      puts 'mail -- timed out while attempting to ' + @event['action'] + ' an incident -- ' + short_name
    end
  end
end
```

event : 
```json
{"event":{"id":"8f2c731b-9fc7-4d07-91b6-6dc6f1cf2503","client":{"subscriptions":["all"],"address":"x.x.x.x","name":"host.name","safe_mode":false,"bind":"127.0.0.1","version":"0.13.1","timestamp":1415180625},"check":{"interval":60,"command":"/usr/lib64/nagios/plugins/check_swap-w35%-c10%","timeout":10,"subscribers":["all"],"handlers":["default","logstash"],"standalone":false,"name":"check_metric_disk_swap","issued":1415180644,"executed":1415180645,"duration":0.006,"output":"SWAPCRITICAL-1%free(0MBoutof1023MB)|swap=0MB;358;102;0;1023\n","status":2,"history":["2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2"]},"occurrences":8980,"action":"create"}}
```

output: 
```
 # cat ~/demo-alert-one-line.log | ./mailer.rb 
/usr/lib/ruby/gems/1.8/gems/sensu-plugin-1.1.0/lib/sensu-handler.rb:125:in `+': can't convert nil into String (TypeError)
        from /usr/lib/ruby/gems/1.8/gems/sensu-plugin-1.1.0/lib/sensu-handler.rb:125:in `filter_silenced'
        from /usr/lib/ruby/gems/1.8/gems/sensu-plugin-1.1.0/lib/sensu-handler.rb:31:in `filter'
        from /usr/lib/ruby/gems/1.8/gems/sensu-plugin-1.1.0/lib/sensu-handler.rb:54
        from ./mailer.rb:64
```

it seems to have something to do with this : 

```
    def filter_silenced
      stashes = [
        ['client', '/silence/' + @event['client']['name']],
        ['check', '/silence/' + @event['client']['name'] + '/' + @event['check']['name']],
        ['check', '/silence/all/' + @event['check']['name']]
      ]
```

Alex

**Comment by melkore** [comment]
I'm also having an issue with using gmail as the email provider.  I've flipped the port between 465 and 587 with no change.  I am using the embedded ruby.

The sensu/config.json handler section looks like this:

```json

"handlers": {
    "default": {
      "type": "set",
      "handlers": [
        "stdout"
      ]
    },
    "stdout": {
      "type": "pipe",
      "command": "cat"
    },
    "mailer": {
      "type": "pipe",
      "command": "/etc/sensu/handlers/mailer.rb -j mailer"
    }
  }


```

The sensu/conf.d/mailer.json looks like this:

```json
{
    "mailer": {
        "admin_gui": "localhost",
        "mail_from": "test_from@example.com",
        "reply_to": "test_from@example.com",
        "delivery_method": "smtp",
        "mail_to": "test_to@example.com",
        "smtp_address": "smtp.google.com",
        "smtp_port": "587",
        "smtp_domain": "example.com",
        "smtp_authentication": "plain",
        "smtp_enable_starttls_auto": "true",
        "smtp_username": "xxx",
        "smtp_password": "xxx"
    }
}


```

The error I see:

```
{"timestamp":"2015-01-08T14:39:58.367832-0600","level":"info","message":"handler output","handler":{"type":"pipe","command":"/etc/sensu/handlers/mailer.rb","name":"mailer"},"output":"/opt/sensu/embedded/lib/ruby/2.0.0/net/smtp.rb:540:in `initialize': getaddrinfo: Name or service not known (SocketError)\n"}

```

**Comment by alex-leonhardt** [comment]
I'm unsure of the magic that made this work - but ... it works now. May have something to do with an updated sensu-handler gem/s etc. and some latest mods (latest as in since I logged this ticket). The config now looks like this (and works): 

```
{
  "mailer": {
    "smtp_domain": "smtp-domain.com",
    "admin_gui": "http://uchiwa:3000/",
    "mail_from": "sensu@localhost",
    "mail_to": "me@domain.com",
    "smtp_port": "25",
    "smtp_address": "localhost",
    "subscriptions": {
      "bess": {
        "mail_to": "other@domain.com"
      }
    }
  },
  "handlers": {
    "mailer": {
      "severities": [
        "ok",
        "warning",
        "critical",
        "unknown"
      ],
      "command": "/etc/sensu/conf.d/nap_handlers/mailer.rb",
      "type": "pipe"
    }
  }
}
```

that was created with the sensu puppet module using : 

```
    sensu::handler { 'mailer':
      command => '/etc/sensu/conf.d/nap_handlers/mailer.rb',
      config  => {
        "admin_gui"     =>  "http://uchiwa:3000/",
        "mail_from"     =>  "sensu@localhost",
        "mail_to"       =>  "me@domain.com",
        "smtp_address"  =>  "localhost",
        "smtp_port"     => "25",
        "smtp_domain"   =>  "smtp-domain.com",
        "subscriptions" => {
          "bess" => {
            "mail_to" => "other@domain.com"
            }
        }
      },
      type    =>  'pipe'
    }
```

Alex

**Comment by chrisduong** [comment]
Hi @alex-leonhardt, I copied your json. But it didn't work. Do you feel the familiar with the error

```
root@abc:~# cat mail-handler.json | /opt/sensu/embedded/bin/ruby /etc/sensu/handlers/notification/mailer.rb -j mailer.json
/etc/sensu/handlers/notification/mailer.rb:77:in `handle': undefined method `[]' for nil:NilClass (NoMethodError)
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.1.0/lib/sensu-handler.rb:55:in `block in <class:Handler>'
root@backup:~#
```

Please help

**Comment by chrisduong** [comment]
I've fixed the issue. It turned out that one of my json file has incorrect format. (I should not put # in the json file)
